language: node_js
node_js:
  - "8"
dist: trusty # should be default but just to be sure
# Cache node_modules
cache:
  directories:
    - "node_modules"
script:
  - npm test
  # todo Install Chrome headless
  - npm run ci-e2e
