language: node_js
node_js:
  - "8"
dist: trusty # should be default but just to be sure
# Cache node_modules
cache:
  directories:
    - "node_modules"
script:
  - npm test
  # todo Install Chrome headless
  - apt-get update && \ DEBIAN_FRONTEND="noninteractive" \
  - apt-get install -y --no-install-recommends \ chromium \ libgconf-2-4 \ openjdk-8-jre-headless \ && rm -rf /var/lib/apt/lists/*
  - dpkg -s chromium
  - dpkg -s java
